######################################################################
#     This workflow will build the Shared.Dependencies of            #
#                         Peereflits                                 #
######################################################################

name: 'Build, test and publish Peereflits.Shared.Dependencies'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  API_KEY : ${{ secrets.PAT_CLASSIC }}
  DOTNET_SOLUTION: src/Peereflits.Shared.Dependencies.sln

jobs:
  build-and-test:
    name: Build & test & publish
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT : Test

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x

    - name: Restore and build
      run: |
        dotnet restore ${{ env.DOTNET_SOLUTION }}
        dotnet build ${{ env.DOTNET_SOLUTION }} --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ${{ env.DOTNET_SOLUTION }} --configuration Release  --no-restore --no-build --verbosity normal

    - name: Pack & Push
      run: |
        dotnet pack ${{ env.DOTNET_SOLUTION }} --configuration Release --no-build --no-restore
        dotnet nuget add source --username peereflits --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/peereflits/index.json"
        dotnet nuget push **/*.nupkg --api-key ${{ env.API_KEY }} --skip-duplicate --source github
